import exiftool
from pathlib import Path
import typer
import os.path
import pandas as pd

app = typer.Typer()

def build_file_list(path: Path) -> list[Path]:
    if not os.path.isfile(path):
        return [Path(os.path.join(currentpath, file)).absolute() for currentpath, _, files in os.walk(path) for file in files]
    return [path.absolute()]

@app.command()
def main(path: str = typer.Option(..., 
                                  help="Path to either a file or a directory (recursively by default) which shall be processed.",
                                  prompt=True), 
        csv: str = typer.Option("output.csv",
                                help="Path to the output csv generated by this script.",
                                prompt=True
                                )) -> int:
    print("Hello ExifTool2CSV User")
    pretty_path : Path = Path(path).absolute()
    print(f"{pretty_path} will be processed.")
    file_list = build_file_list(pretty_path)
    output = pd.DataFrame()
    with exiftool.ExifTool() as et:
        for file in file_list:
            out = pd.DataFrame(et.execute_json(*[f"{str(file)}"]))
            output = pd.concat([output,out]).reset_index(drop=True)
    output = output.dropna(axis=1, how="all")
    output.to_csv(csv)
    return 0

if __name__ == "__main__":
    app()